# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xBlog', '0007_auto_20160323_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xBlog.Article'),
        ),
    ]
