# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xBlog', '0010_auto_20160323_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xBlog.Article')),
            ],
        ),
        migrations.AlterField(
            model_name='visitor',
            name='articles',
            field=models.ManyToManyField(to='xBlog.Article'),
        ),
        migrations.AddField(
            model_name='readrecord',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xBlog.Visitor'),
        ),
    ]
