# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xBlog', '0011_auto_20160323_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment_nums',
        ),
        migrations.RemoveField(
            model_name='article',
            name='read_nums',
        ),
    ]
