# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xBlog', '0012_auto_20160407_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='articles',
        ),
    ]
