# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xBlog', '0013_remove_visitor_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
